# Generated by Django 4.0.5 on 2022-06-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='no_exp_pass_status',
            field=models.CharField(choices=[('WAIT_SOFT_ADDING', 'Wait Soft Adding'), ('INIT', 'Init'), ('WAIT_PERFORMING', 'Wait Performing'), ('PERFORMING', 'Performing'), ('BRUTED', 'Bruted'), ('ERROR', 'Error')], default='WAIT_SOFT_ADDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='domain',
            name='ntlm_status',
            field=models.CharField(choices=[('WAIT_SOFT_ADDING', 'Wait Soft Adding'), ('INIT', 'Init'), ('WAIT_PERFORMING', 'Wait Performing'), ('PERFORMING', 'Performing'), ('BRUTED', 'Bruted'), ('ERROR', 'Error')], default='WAIT_SOFT_ADDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='domain',
            name='reused_pass_status',
            field=models.CharField(choices=[('WAIT_SOFT_ADDING', 'Wait Soft Adding'), ('INIT', 'Init'), ('WAIT_PERFORMING', 'Wait Performing'), ('PERFORMING', 'Performing'), ('BRUTED', 'Bruted'), ('ERROR', 'Error')], default='WAIT_SOFT_ADDING', max_length=20),
        ),
    ]
