# Generated by Django 4.0.5 on 2022-06-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_cabinet', '0002_alter_domain_no_exp_pass_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrutedNTLMAccs',
            new_name='BrutedNTLMAcc',
        ),
        migrations.RenameModel(
            old_name='ReusedPassAccs',
            new_name='NoExpPassAcc',
        ),
        migrations.RenameModel(
            old_name='NoExpPassAccs',
            new_name='ReusedPassAcc',
        ),
    ]
