# Generated by Django 4.0.5 on 2022-07-07 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cabinet', '0003_rename_brutedntlmaccs_brutedntlmacc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='ntlm_error_desc',
            new_name='brute_error_desc',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='ntlm_progress',
            new_name='brute_progress',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='ntlm_status_update',
            new_name='brute_status_update',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='fqdn',
            new_name='hostname',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='acc_password',
            new_name='user_password',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='acc_login',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='ntlm_status',
        ),
        migrations.AddField(
            model_name='domain',
            name='base_dn',
            field=models.CharField(default='test', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domain',
            name='brute_status',
            field=models.CharField(choices=[('WAIT_SOFT_ADDING', 'Wait Soft Adding'), ('INIT', 'Init'), ('WAIT_PERFORMING', 'Wait Performing'), ('PERFORMING', 'Performing'), ('FINISHED', 'Finished'), ('ERROR', 'Error')], default='WAIT_SOFT_ADDING', max_length=20),
        ),
        migrations.AddField(
            model_name='domain',
            name='dump_err_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='dump_status',
            field=models.CharField(choices=[('WAIT_SOFT_ADDING', 'Wait Soft Adding'), ('INIT', 'Init'), ('WAIT_PERFORMING', 'Wait Performing'), ('PERFORMING', 'Performing'), ('FINISHED', 'Finished'), ('ERROR', 'Error')], default='WAIT_SOFT_ADDING', max_length=20),
        ),
        migrations.AddField(
            model_name='domain',
            name='dump_status_update',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='domain',
            name='name',
            field=models.CharField(default='test_name', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domain',
            name='user_dn',
            field=models.CharField(default='test_user_dn', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domain',
            name='workstation_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='workstation_password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='no_exp_pass_status',
            field=models.CharField(choices=[('WAIT_SOFT_ADDING', 'Wait Soft Adding'), ('INIT', 'Init'), ('WAIT_PERFORMING', 'Wait Performing'), ('PERFORMING', 'Performing'), ('FINISHED', 'Finished'), ('ERROR', 'Error')], default='WAIT_SOFT_ADDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='domain',
            name='reused_pass_status',
            field=models.CharField(choices=[('WAIT_SOFT_ADDING', 'Wait Soft Adding'), ('INIT', 'Init'), ('WAIT_PERFORMING', 'Wait Performing'), ('PERFORMING', 'Performing'), ('FINISHED', 'Finished'), ('ERROR', 'Error')], default='WAIT_SOFT_ADDING', max_length=20),
        ),
    ]
