# Generated by Django 4.0.5 on 2022-07-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cabinet', '0004_rename_ntlm_error_desc_domain_brute_error_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='base_dn',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='domain',
            name='brute_status',
            field=models.CharField(choices=[('INIT', 'Init'), ('WAIT_PERFORMING', 'Wait Performing'), ('PERFORMING', 'Performing'), ('FINISHED', 'Finished'), ('ERROR', 'Error')], default='INIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='domain',
            name='dump_status',
            field=models.CharField(choices=[('INIT', 'Init'), ('WAIT_PERFORMING', 'Wait Performing'), ('PERFORMING', 'Performing'), ('FINISHED', 'Finished'), ('ERROR', 'Error')], default='INIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='domain',
            name='hostname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='domain',
            name='no_exp_pass_status',
            field=models.CharField(choices=[('INIT', 'Init'), ('WAIT_PERFORMING', 'Wait Performing'), ('PERFORMING', 'Performing'), ('FINISHED', 'Finished'), ('ERROR', 'Error')], default='INIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='domain',
            name='reused_pass_status',
            field=models.CharField(choices=[('INIT', 'Init'), ('WAIT_PERFORMING', 'Wait Performing'), ('PERFORMING', 'Performing'), ('FINISHED', 'Finished'), ('ERROR', 'Error')], default='INIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='domain',
            name='user_dn',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='domain',
            name='user_password',
            field=models.CharField(default='lll', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domain',
            name='workstation_name',
            field=models.CharField(default='llll', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domain',
            name='workstation_password',
            field=models.CharField(default='123123', max_length=128),
            preserve_default=False,
        ),
    ]
