# Generated by Django 4.0.5 on 2022-07-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cabinet', '0005_alter_domain_base_dn_alter_domain_brute_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brutedntlmacc',
            name='sam_acc_name',
            field=models.CharField(max_length=30),
        ),
    ]
