# Generated by Django 4.0.5 on 2022-07-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cabinet', '0007_alter_brutedntlmacc_domain_alter_noexppassacc_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noexppassacc',
            name='sam_acc_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reusedpassacc',
            name='sam_acc_name',
            field=models.CharField(max_length=30),
        ),
    ]
