# Generated by Django 4.0.5 on 2022-07-13 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_cabinet', '0008_alter_noexppassacc_sam_acc_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reusedpassacc',
            name='reused_pass_domain',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user_cabinet.domain'),
            preserve_default=False,
        ),
    ]
