# Generated by Django 4.0.5 on 2022-07-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_cabinet', '0009_reusedpassacc_reused_pass_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reusedpassacc',
            old_name='reused_pass_domain',
            new_name='reused_domain',
        ),
        migrations.AddField(
            model_name='reusedpassacc',
            name='reused_sam_acc_name',
            field=models.CharField(default='TEST', max_length=30),
            preserve_default=False,
        ),
    ]
